Application=E-Commerce Application
Environment=QA
URL=https://rahulshettyacademy.com/client
Automation.Framework=Playwright Python
Test.Framework=Pytest
BDD.Framework=Pytest-BDD
Reporting=Allure
Browser=Chromium
Operating.System=Windows 11
Python.Version=3.13
Author=Sagar_Shinde
